### ISSUE TITLE
Support bower

### ISSUE THREAD

**Issue by lyyourc** [bitinn/kneesocks#1]
I think it's a good ideal.

**Comment by bitinn** [comment]
Could you give a use-case for bower? there isn't a `-g` equivalent for bower.

**Comment by lyyourc** [comment]
W/hen I use bower, for instance, `bower install angular --save`, the speed of the download is quite slow. So I hope that it can download through shadowsocks.  @bitinn

**Comment by bitinn** [comment]
does bower support http proxy then? if so, you can already do the same thing as npm, just set it up to use your http proxy host and port. let me know this it works.

http://stackoverflow.com/questions/21705091/bower-behind-a-proxy
