### ISSUE TITLE
Error in use

### ISSUE THREAD

**Issue by jaeheng** [bitinn/kneesocks#3]
operating system:window 7 64
nodejs : v5.10.1
## npm : 3.8.7

![image](https://cloud.githubusercontent.com/assets/7394473/15638187/d468c19e-264f-11e6-88bd-fc4721ee9f5d.png)

**Comment by wuseal** [comment]
the same as me

**Comment by jaeheng** [comment]
@wuseal just install the ipv6 module

``` shell
npm install -g ipv6
```

**Comment by bitinn** [comment]
fixed in v1.0.4, sorry for the delay
