### ISSUE TITLE
请问 npm 支持 Shadowsocks 的 PAC 模式吗？

### ISSUE THREAD

**Issue by Loyalsoldier** [bitinn/kneesocks#4]
Shadowsocks-windows 提供了 socks5 和 http 两个代理，所以在 Windows 上设置 npm 代理其实不成问题。

问题是，如果 npm 使用了淘宝源，这时候如果再用代理，就特别慢。而如果不用代理，一些需要从亚马逊 S3 云服务器上下载的 tarball 就会下载特别龟速。

所以，更希望 npm 能支持 Shadowsocks 的 PAC 模式~不知道有没有头绪？

**Comment by bitinn** [comment]
sorry, no support for that, your socks server should handle request routing altogether (though I understand some implementations doesn't have that).
